### ISSUE TITLE
Cannot use Promise.defer

### ISSUE THREAD

**Issue by szlaskidaniel** [coreybutler/node-windows#167] opened 2017-04-07 14:00 UTC
node app.js works brilliant.
When the same app.js is wrapped by node-windows - I've got errors that
"Promise.defer is not a function"

**Comment by coreybutler** [comment] 2017-04-07 22:01
https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why

**Comment by szlaskidaniel** [comment] 2017-04-10 08:52
Hi, thx for link, but I do not believe that it's __dirname issue.
Script launched properly, the error is related to the word "Promise.defer();" 
return new Promise works fine, but it do not work with older one, which is Promise.defer();

**Comment by coreybutler** [comment] 2017-04-10 16:05
A wrapper like node-windows won't cause a problem with native JS (which promises are). I'm confident this is an application issue, not a node-windows issue, so I'm going to close this. I'd suggest posting on StackOverflow with more detail about your specific case.... it's hard to even guess at what the problem is when we can't see any code. Once you've done this, feel free to put the link in here and I'll look at it as time allows.

**Closed by coreybutler** 2017-04-10 16:05 UTC
