### ISSUE TITLE
Child Process Terminated with 0

### ISSUE THREAD

**Issue by RobertSmart** [coreybutler/node-windows#90] opened 2015-05-13 16:07 UTC
Hi,

I'm using node-windows to install a script on a windows (server 2012 R2). 

The script runs fine when run from the node cmd line. 

The service seems to install fine, but on starting the service it stops immediately with this:

Child process [4016 - C:\Program Files\nodejs\node.exe --harmony "#MYFILEPATH#\node_modules\node-windows\lib\wrapper.js" -f #MYFILEPATH#\#MYSCRIPT#.js" -l "#SCRIPTNAME#" -g 0.25 -w 1 -r 3 -a n] terminated with 0

I have tried it on another non-server machine and works ok, Is there any settings on a server machine that would effect this?

Thanks

**Comment by coreybutler** [comment] 2015-05-13 18:32
The most common reason for this type of behavior is the configuration of a path. For example, a lot of people use `__dirname` to define a path, which can differ between a child and parent process. As the documentation suggests, it is always best to use absolute paths.

The other common issue I see is a misunderstanding of how a module is used within an app. Some modules make assumptions about the context in which they're running. 

I'm not saying either of these are the cause of your problem, but these are the most common reasons I see these issues creep up.

**Comment by coreybutler** [comment] 2015-05-25 15:56
I've added a [wiki entry](https://github.com/coreybutler/node-windows/wiki#my-script-runs-fine-on-its-own-but-not-with-node-windows-why) for this. I'm going to close this, but if your question isn't answered, please feel free to reopen.

**Closed by coreybutler** 2015-05-25 15:56 UTC
