### ISSUE TITLE
Run command by sudoer in windows os

### ISSUE THREAD

**Issue by tinvm** [coreybutler/node-windows#172] opened 2017-05-18 08:26 UTC
Hi Corey Butler,

Many thanks for creating the package. It's very handing with us.
However, I have not the way to run by sudoer in windows os. Can you help me this? pls thanks

**Comment by coreybutler** [comment] 2017-05-19 19:30
Since this is a question and not a bug, I'm closing it. I've also provided an answer on the Gitter channel.

**Closed** 2017-05-19 19:33 UTC
Labels: question (better for stackoverflow)
