### ISSUE TITLE
v1.0.0-beta.7 fails to start process

### ISSUE THREAD

**Issue by seidhkona** [coreybutler/node-windows#313] opened 2022-04-20 16:37 UTC
This is already reported in Discussions, but I haven't found an open issue related to this. 

When I start the process using node-windows@1.0.0-beta.6 - the service is created and starts.
If I upgrade to node-windows@1.0.0-beta.7 - the service is created, but will not start: Error: 1067

**Comment by coreybutler** [comment] 2022-04-20 21:25
It's not easy to tell based on the title of the other issue, but this is a duplicate of #308.

**Closed by coreybutler** 2022-04-20 21:25 UTC
Labels: duplicate
