### ISSUE TITLE
child.send -  Cannot read property  'send'  of null

### ISSUE THREAD

**Issue by srconklin** [coreybutler/node-windows#166] opened 2017-03-25 01:35 UTC
When running the install example to create a windows service, I see the service created in services, but exits immediately when trying to start it. I note that I don't have an .exe file in the daemon folder and the .err.log file has following error:

Could you help interpret this and advise what to do? 

[server.zip](https://github.com/coreybutler/node-windows/files/869558/server.zip)

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\Users\scott\AppData\Roaming\npm\node_modules\node-windows\lib\wrapper.js:177:10)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at monitor (C:\Users\scott\AppData\Roaming\npm\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\Users\scott\AppData\Roaming\npm\node_modules\node-windows\lib\wrapper.js:170:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
C:\Users\scott\AppData\Roaming\npm\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');

attached is the .js file I am trying to create a service out of.

CORRECTION: I do have the exe file in the Daemon folder.

**Comment by srconklin** [comment] 2017-03-29 17:11
I am thinking this has something to do with the nature of  node-msmq ].... any thoughts? 
Was hoping you had some thoughts on why this fails to start

**Comment by coreybutler** [comment] 2017-03-29 17:58
Have you seen the [wiki](https://github.com/coreybutler/node-windows/wiki)?

**Comment by srconklin** [comment] 2017-03-29 18:21
Yes, I have seen this. I have the symptoms of the first and last wiki entries (no error in the logs at all) but am not using in variables to define paths. The script (below) is  very simple with absolute paths. So I am guessing it is something about the context of node node-msmq  as you mention.. 

Thanks for trying

```

const msmq = require('node-msmq');
const  fs = require('fs');

var queue = msmq.openOrCreateQueue('.\\private$\\testqueue');

// Set receive listener callback
queue.on('receive', (msg) => {
  console.log(msg.body);
  fs.writeFileSync("C:\\tmp\\test.xml", msg.body); 
});
console.log('listening for messages..');
// Start receiving messages from the queue
queue.startReceiving();

```

**Comment by coreybutler** [comment] 2017-04-10 16:16
I'm going to close this since it seems to be specific to node-msmq, but the key line I see that catches my attention is `var queue = msmq.openOrCreateQueue('.\\private$\\testqueue');`, which looks like a relative path. I'd suggest using either a hard coded path or something like:

`var queue = msmq.openOrCreateQueue(require(path').join(process.cwd(), 'private$', 'testqueue'));`

That would generate an absolute path using the current working directory (wherever the script is being run from).

If you find that the issue is indeed node-windows, feel free to re-open.

**Closed by coreybutler** 2017-04-10 16:16 UTC

**Comment by srconklin** [comment] 2017-04-10 17:08
thanks for that tip!  I will try that
